import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-white text-amazon-text flex flex-col min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
