import Footer from "@/components/footer/Footer";
import Providers from "./providers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-amazon-text flex flex-col min-h-screen">
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}

// "use client";

// import { signOut } from "next-auth/react";

// export default function SignOutButton() {
//   return (
//     <button
//       type="button"
//       className="px-4 py-2 rounded-sm bg-gray-900 text-white text-sm"
//       onClick={() => signOut({ callbackUrl: "/login" })}
//     >
//       Logout
//     </button>
//   );
// }
